# Generated by Django 5.1.6 on 2025-02-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id_capacity',
            new_name='capacity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='uom_id',
            new_name='unit_of_measure',
        ),
        migrations.RenameField(
            model_name='relstoreprice',
            old_name='id_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='relstoreprice',
            old_name='id_store',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='relstoreprice',
            old_name='taxe_rate_id',
            new_name='taxe_rate',
        ),
        migrations.AlterField(
            model_name='capacity',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productstate',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relstoreprice',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxerate',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
