# Generated by Django 5.1.6 on 2025-02-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_id_capacity_product_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(blank=True, db_column='latitude', decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(blank=True, db_column='longitude', decimal_places=6, max_digits=9, null=True),
        ),
    ]
